version: "3.8"

services:
  netmaker:
    image: gravitl/netmaker
    container_name: netmaker
    restart: always
    env_file:
      - .env
    ports:
      - "51821:51821/udp"   # WireGuard
      - "80:80"             # Painel admin HTTP
      - "443:443"           # Painel admin HTTPS
    volumes:
      - netmaker-data:/data
    command: /bin/sh -c "netmaker server --auto-setup"  # Auto setup completo

volumes:
  netmaker-data:
